#ifndef __EVAL1A_CONFIG_H
#define __EVAL1A_CONFIG_H

#include "mx6_common.h"

#ifndef CONFIG_MXC_UART
#define CONFIG_MXC_UART
#endif

/*
#define CONFIG_SPL
#define CONFIG_SPL_BUILD
#define CONFIG_SPL_FRAMEWORK
#define CONFIG_SYS_ONENAND_BASE 0x4E000000
#define CONFIG_SPL_TEXT_BASE 0x0
#define CONFIG_SPL_SKIP_RELOCATE
#define CONFIG_SPL_SERIAL_SUPPORT
*/

#define CONFIG_ENV_SIZE			SZ_8K
#define CONFIG_ENV_OFFSET		(12 * SZ_64K)

#define CONFIG_MXC_UART_BASE	UART1_BASE

//#define CONFIG_FEC_MXC
#define IMX_FEC_BASE			ENET_BASE_ADDR
#define CONFIG_FEC_ENET_DEV		1
#define CONFIG_FEC_MXC_PHYADDR  0x2
#define CONFIG_FEC_XCV_TYPE     RMII
#define CONFIG_ETHPRIME			"eth0"


/* MMC Configs */
#ifdef CONFIG_FSL_USDHC
#define CONFIG_SYS_FSL_ESDHC_ADDR	USDHC1_BASE_ADDR
#endif

#define PHYS_SDRAM_SIZE	SZ_256M

#define CONFIG_SYS_MALLOC_LEN		(16 * SZ_1M)

/* Physical Memory Map */
#define PHYS_SDRAM			MMDC0_ARB_BASE_ADDR

#define CONFIG_SYS_SDRAM_BASE		PHYS_SDRAM
#define CONFIG_SYS_INIT_RAM_ADDR	IRAM_BASE_ADDR
#define CONFIG_SYS_INIT_RAM_SIZE	IRAM_SIZE

#define CONFIG_SYS_INIT_SP_OFFSET \
	(CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)

#define CONFIG_SYS_INIT_SP_ADDR \
	(CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)


#endif
